-----------------------
#!/usr/bin/python
#A simple try-except:
try:
  print(x)
except:
  print("An exception occurred")
-----------------------
#!/usr/bin/python
#A try-except with many excepts:
try:
  print(x)
except NameError:
  print("Variable x is not defined")
except:
  print("Something else went wrong")
-----------------------
#!/usr/bin/python
#The else block will be executed when there is no error:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")
-----------------------
#!/usr/bin/python
#The finally block executes regardless if the try block raises an error:
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")